on:
  release:
    types: [published]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      # Checkout the repository under a subdirectory (repository-name/) to
      # make zipping easier. Note: 'gh' or 'git' commands must be executed
      # *after* changing into the repository's directory.
      - uses: actions/checkout@v4
        with:
          path: ${{ github.event.repository.name }}

      # Create a filtered zip of the repository.
      - name: Zip Repository (excludes .git*)
        run: |
          cd ${{ github.event.repository.name }}
          mv blender ${{ github.event.repository.name }}
          zip -r ${{ github.event.repository.name }}.${{ github.event.release.tag_name }}.blender.zip \
            ${{ github.event.repository.name }} \
            -x "${{ github.event.repository.name }}/.git*"          
      
      # Create a new GitHub release using the tag name or commit id.
      - name: Create versioned build with filtered zip file.
        run: |
          cd ${{ github.event.repository.name }}
          gh release upload ${{github.ref_name}} \
            ${{ github.event.repository.name }}.${{ github.event.release.tag_name }}.blender.zip
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
